#!/bin/bash

set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

target=${ENV_NAME}
task=${1}

export CF_API="https://api.$target.garden-dev.cf-app.com"
export CF_USERNAME=admin
export CF_PASSWORD
CF_PASSWORD="$(bosh int --path=/cf_admin_password "$HOME/workspace/garden-ci/directors/$target/deployments/cf-vars.yml")"

fly -t "$GARDEN_REMOTE_ATC_URL" execute \
  -c "$DIR/../ci/$task" \
  -i cpu-entitlement-plugin="$DIR/.." \
  -i spinner="$DIR/../../spinner"
