// Code generated by counterfeiter. DO NOT EDIT.
package orgfakes

import (
	"sync"

	"code.cloudfoundry.org/cpu-entitlement-plugin/plugins/org"
	"code.cloudfoundry.org/cpu-entitlement-plugin/reporter"
)

type FakeRenderer struct {
	RenderStub        func(reporter.OEIReport) error
	renderMutex       sync.RWMutex
	renderArgsForCall []struct {
		arg1 reporter.OEIReport
	}
	renderReturns struct {
		result1 error
	}
	renderReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRenderer) Render(arg1 reporter.OEIReport) error {
	fake.renderMutex.Lock()
	ret, specificReturn := fake.renderReturnsOnCall[len(fake.renderArgsForCall)]
	fake.renderArgsForCall = append(fake.renderArgsForCall, struct {
		arg1 reporter.OEIReport
	}{arg1})
	fake.recordInvocation("Render", []interface{}{arg1})
	fake.renderMutex.Unlock()
	if fake.RenderStub != nil {
		return fake.RenderStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.renderReturns
	return fakeReturns.result1
}

func (fake *FakeRenderer) RenderCallCount() int {
	fake.renderMutex.RLock()
	defer fake.renderMutex.RUnlock()
	return len(fake.renderArgsForCall)
}

func (fake *FakeRenderer) RenderCalls(stub func(reporter.OEIReport) error) {
	fake.renderMutex.Lock()
	defer fake.renderMutex.Unlock()
	fake.RenderStub = stub
}

func (fake *FakeRenderer) RenderArgsForCall(i int) reporter.OEIReport {
	fake.renderMutex.RLock()
	defer fake.renderMutex.RUnlock()
	argsForCall := fake.renderArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRenderer) RenderReturns(result1 error) {
	fake.renderMutex.Lock()
	defer fake.renderMutex.Unlock()
	fake.RenderStub = nil
	fake.renderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRenderer) RenderReturnsOnCall(i int, result1 error) {
	fake.renderMutex.Lock()
	defer fake.renderMutex.Unlock()
	fake.RenderStub = nil
	if fake.renderReturnsOnCall == nil {
		fake.renderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.renderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRenderer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.renderMutex.RLock()
	defer fake.renderMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRenderer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ org.Renderer = new(FakeRenderer)
